"""Test fixtures + fake services for integration tests.

The fake_nominatim_results.json file contains 10 POIs whose lat/lon were
generated by projecting METER offsets through pyproj (always_xy=True), so
distances behave realistically when fed through the real geometry helpers.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from app.models import Poi, RouteResult
from app.services.geometry import build_meter_transformers


FIXTURE_DIR = Path(__file__).parent
_BASE_LAT = 25.0330
_BASE_LON = 121.5654
_TO_M, _TO_WGS = build_meter_transformers(_BASE_LON, _BASE_LAT)


# ---------------------------------------------------------------------------
# POI loader
# ---------------------------------------------------------------------------

def load_fake_pois() -> list[Poi]:
    """Load the JSON fixture and rebuild Poi objects (owner=None)."""
    data = json.loads(
        (FIXTURE_DIR / "fake_nominatim_results.json").read_text(encoding="utf-8")
    )
    pois: list[Poi] = []
    for d in data:
        pois.append(Poi(
            id=d["id"],
            name=d["name"],
            lat=float(d["lat"]),
            lon=float(d["lon"]),
            osm_type=d.get("osm_type"),
            osm_id=d.get("osm_id"),
            category=d["category"],
            poi_type=d["poi_type"],
            score=int(d["score"]),
            owner=None,
            discovered_turn=None,
            placed_turn=None,
            raw={"name": d["name"]},
        ))
    return pois


def pois_by_id(pois: list[Poi]) -> dict[str, Poi]:
    return {p.id: p for p in pois}


# ---------------------------------------------------------------------------
# Route fixture helper — interpolate between two POIs using pyproj
# ---------------------------------------------------------------------------

def make_fake_route(
    from_poi: Poi,
    to_poi: Poi,
    duration_s: float,
    distance_m: float | None = None,
    n_points: int = 5,
) -> RouteResult:
    """Build a straight-line RouteResult between two POIs (lon, lat preserved)."""
    ax, ay = _TO_M.transform(from_poi.lon, from_poi.lat)
    bx, by = _TO_M.transform(to_poi.lon, to_poi.lat)
    coords: list[list[float]] = []
    for i in range(n_points):
        t = i / (n_points - 1)
        x = ax + (bx - ax) * t
        y = ay + (by - ay) * t
        lon, lat = _TO_WGS.transform(x, y)
        coords.append([lon, lat])

    if distance_m is None:
        # Straight-line meters between endpoints — good enough for tests
        distance_m = ((bx - ax) ** 2 + (by - ay) ** 2) ** 0.5

    return RouteResult(
        coordinates_lonlat=coords,
        distance_m=float(distance_m),
        duration_s=float(duration_s),
    )


# ---------------------------------------------------------------------------
# Fake services
# ---------------------------------------------------------------------------

@dataclass
class FakeNominatim:
    """Returns canned POIs (full list by default); honours an optional filter callable."""
    results: list[Poi] = field(default_factory=list)
    error: Exception | None = None
    calls: list[tuple] = field(default_factory=list)

    def search(
        self,
        query: str,
        center_lat: float | None = None,
        center_lon: float | None = None,
        search_km: float | None = None,
        limit: int = 10,
    ) -> list[Poi]:
        self.calls.append((query, center_lat, center_lon, search_km, limit))
        if self.error is not None:
            raise self.error
        return list(self.results)


@dataclass
class FakeOsrm:
    """OSRM stand-in. Routes are registered explicitly; unknown calls raise.

    `register(from_poi, to_poi, duration_s)` is the main API.
    `register_failure(...)` simulates network/HTTP failure as an exception.
    """
    routes: dict = field(default_factory=dict)
    calls: list[tuple] = field(default_factory=list)

    @staticmethod
    def _key(fl, fn, tl, tn) -> tuple:
        return (round(fl, 7), round(fn, 7), round(tl, 7), round(tn, 7))

    def register(self, from_poi: Poi, to_poi: Poi, duration_s: float) -> RouteResult:
        rr = make_fake_route(from_poi, to_poi, duration_s)
        self.routes[self._key(from_poi.lat, from_poi.lon, to_poi.lat, to_poi.lon)] = rr
        return rr

    def register_failure(self, from_poi: Poi, to_poi: Poi, exc: Exception) -> None:
        self.routes[self._key(from_poi.lat, from_poi.lon, to_poi.lat, to_poi.lon)] = exc

    def route(self, from_lat, from_lon, to_lat, to_lon) -> RouteResult:
        self.calls.append((from_lat, from_lon, to_lat, to_lon))
        key = self._key(from_lat, from_lon, to_lat, to_lon)
        if key not in self.routes:
            raise RuntimeError(
                f"FakeOsrm: unexpected call {key} (registered: {list(self.routes)})"
            )
        val = self.routes[key]
        if isinstance(val, Exception):
            raise val
        return val
